#!/usr/bin/env bash
# Render the o11y bundle into <output-dir>:
#   folder.yaml            one GrafanaFolder, the project boundary in Grafana
#   dashboards/<uid>.yaml  each o11y/dashboards/<uid>.json as a self-contained
#                          GrafanaDashboard CR (JSON as gzip+base64 in spec.gzipJson)
#   alerts/*.yaml          GrafanaAlertRuleGroup CRs from o11y/alerts, as-is
#   rules/*.yaml           VMRule CRs from o11y/rules, as-is; evaluated by the
#                          version tenant's vmalert on the o11y clusters
#
# CI pushes that directory as one signed OCI artifact, and the o11y clusters apply
# it with a Flux OCIRepository + Kustomization (Model A in yucca-o11y
# docs/06-dashboards-and-alerts-guide.md). No kustomization.yaml is emitted:
# kustomize-controller generates one for a directory of plain manifests. The
# output is build output; o11y/ is the source of truth.
#
# Ported from immich-app/yucca .github/scripts/render-o11y-manifests.sh and
# fmeet.futo.org o11y/render-manifests.sh; the rules/ pass is new.
set -euo pipefail

out=${1:?usage: render-manifests.sh <output-dir>}
src=$(cd "$(dirname "$0")" && pwd)

# The folder, the `project` label on every series and every alert rule, and the
# tenant label on every VMRule are all this one name. o11y routes alerts on
# project first and grafana_folder (the folder title) second.
project=version
# The label the version tenant's vmalert selects VMRules by. o11y stamps it on
# everything in this bundle too (yucca-o11y kubernetes/apps/base/tenants/version).
tenant_label=o11y.futo.org/tenant

rm -rf "$out"
mkdir -p "$out/dashboards"

cat >"$out/folder.yaml" <<EOF
# generated by o11y/render-manifests.sh in immich-app/version; do not edit
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: ${project}
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  resyncPeriod: 10m
  title: ${project}
EOF

dashboards=0
for f in "$src"/dashboards/*.json; do
  # The file name, the dashboard's uid and metadata.name must agree on one
  # DNS-1123 name: deep links resolve against the uid, and a mismatch silently
  # creates a second dashboard on the next sync instead of updating this one.
  uid=$(basename "$f" .json)
  if [ "$(jq -r .uid "$f")" != "$uid" ] || [ "$uid" = folder ] ||
    ! printf '%s' "$uid" | grep -Eq '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'; then
    echo "$f: uid must be a DNS-1123 name matching the file name, and not 'folder'" >&2
    exit 1
  fi
  jq -e '.title and (.panels | length > 0)' "$f" >/dev/null ||
    { echo "$f: dashboard needs a title and panels" >&2; exit 1; }
  # Every query goes through $datasource, which defaults to VictoriaMetricsFleet.
  # A hard-coded uid points at nothing on o11y, or at the default VictoriaMetrics
  # datasource, which only serves the o11y cluster's own tenant: empty panels.
  baked=$(jq -r '[.. | objects | select(has("datasource")) | .datasource
      | if type == "object" then .uid else . end | select(. != null)
      | select(. != "${datasource}" and . != "$datasource" and . != "-- Grafana --")]
    | unique | join(", ")' "$f")
  if [ -n "$baked" ]; then
    echo "$f: hard-coded datasource uid(s) ${baked}; use \${datasource}" >&2
    exit 1
  fi
  jq -e '[.templating.list[]? | select(.name == "datasource" and .type == "datasource"
      and .current.value == "VictoriaMetricsFleet")] | length == 1' "$f" >/dev/null ||
    { echo "$f: needs a \$datasource variable defaulting to VictoriaMetricsFleet" >&2; exit 1; }
  # gzip -n drops the name and mtime so unchanged JSON renders byte-identical and
  # the artifact digest stays put. base64 | tr is a portable no-wrap. Embedding it
  # also keeps the JSON's ${datasource} away from Flux's variable substitution.
  gz=$(gzip -nc "$f" | base64 | tr -d '\n')
  cat >"$out/dashboards/${uid}.yaml" <<EOF
# generated from o11y/dashboards/${uid}.json in immich-app/version; do not edit
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: ${uid}
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  resyncPeriod: 10m
  folderRef: ${project}
  gzipJson: ${gz}
EOF
  dashboards=$((dashboards + 1))
done

# Flux substitutes ${VAR} in everything o11y applies (an unknown name becomes an
# empty string), so plain YAML must not contain one.
no_substitution() {
  if grep -n '\${' "$1" >&2; then
    echo "$1: contains \${ which Flux would substitute on o11y" >&2
    exit 1
  fi
}

# yq -e judges only the last document of a file, so a second document would
# reach o11y without passing the checks below.
single_document() {
  if [ "$(yq ea '[.] | length' "$1")" != 1 ]; then
    echo "$1: exactly one YAML document per file" >&2
    exit 1
  fi
}

alerts=0
if compgen -G "$src/alerts/*.yaml" >/dev/null; then
  mkdir -p "$out/alerts"
  for f in "$src"/alerts/*.yaml; do
    no_substitution "$f"
    single_document "$f"
    yq -e '.kind == "GrafanaAlertRuleGroup"
      and .metadata.namespace == null
      and .spec.folderRef == "'"$project"'"
      and ([.spec.rules[] | select(.labels.project != "'"$project"'" or .labels.severity == null or .labels.heartbeat != null)] | length == 0)
      and ([.spec.rules[].data[] | select(.datasourceUid != "__expr__" and .datasourceUid != "VictoriaMetricsFleet")] | length == 0)' \
      "$f" >/dev/null || {
      echo "$f: one GrafanaAlertRuleGroup per file, no namespace, folderRef: ${project}, every rule labelled project: ${project} and severity (never heartbeat), every query on VictoriaMetricsFleet" >&2
      exit 1
    }
    cp "$f" "$out/alerts/"
    alerts=$((alerts + 1))
  done
fi

rules=0
if compgen -G "$src/rules/*.yaml" >/dev/null; then
  mkdir -p "$out/rules"
  for f in "$src"/rules/*.yaml; do
    no_substitution "$f"
    single_document "$f"
    # The version tenant's vmalert writes results back with the identity labels
    # as externalLabels, which is what files them under tenant 7:1. A group's or
    # rule's own `labels:` override externalLabels, though (vmalert merges
    # external, then group, then rule labels), so a `project` or `cluster` there
    # would write the results into another tenant, and o11y does not stop it.
    # vm_account_id/vm_project_id would pick the tenant on /insert/multitenant.
    yq -e '.kind == "VMRule"
      and .metadata.namespace == null
      and .metadata.labels["'"$tenant_label"'"] == "'"$project"'"
      and ([.spec.groups[] | select(.tenant != null)] | length == 0)
      and ([.spec.groups[] | ((.labels // {}), (.rules[] | (.labels // {}))) | keys | .[]
        | select(. == "project" or . == "cluster" or . == "env" or . == "provider" or . == "region"
          or . == "vm_account_id" or . == "vm_project_id")] | length == 0)' \
      "$f" >/dev/null || {
      echo "$f: one VMRule per file, no namespace, labelled ${tenant_label}: ${project}, no group tenant, no project/cluster/env/provider/region/vm_* in group or rule labels (they override vmalert's externalLabels and re-route results to another tenant)" >&2
      exit 1
    }
    cp "$f" "$out/rules/"
    rules=$((rules + 1))
  done
fi

echo "rendered GrafanaFolder ${project}, ${dashboards} dashboards, ${alerts} alert groups and ${rules} VMRules into ${out}"
